// This file is generated by the rs-update-tests script

#include "rs-unit-test.hpp"

int main(int argc, char** argv) {

    RS::UnitTest::begin_tests(argc, argv);

    // dso-test.cpp
    UNIT_TEST(rs_system_dynamic_library)

    // unit-test.cpp

    // version-test.cpp
    UNIT_TEST(rs_system_version)

    return RS::UnitTest::end_tests();

}
